name: snipvoice
description: SnipVoice - tek tusla trade voice journal. Bas-konus-dinle.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  record: ^7.1.1
  just_audio: ^0.10.6
  audio_session: ^0.2.4
  path_provider: ^2.1.4
  table_calendar: ^3.1.2
  intl: 0.20.3
  uuid: ^4.5.1
  supabase_flutter: ^2.5.6
  timezone: ^0.9.4
  flutter_dotenv: ^5.1.0
  file_picker: ^13.1.0
  shared_preferences: ^2.5.5
  flutter_localizations:
    sdk: flutter
  share_plus: ^13.3.0
  open_filex: ^4.7.0
  just_audio_windows: ^0.2.3
  permission_handler: 11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: true
  ios: false
  windows:
    generate: true
    image_path: assets/logo.png
    icon_size: 48
  image_path: assets/logo.png
